# Copyright (c) 2021 Tailscale Inc & AUTHORS All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
name: 'Connect Tailscale'
description: 'Connect your GitHub Action workflow to Tailscale'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
inputs:
  authkey:
    description: 'Your Tailscale authentication key, from the admin panel.'
    required: true
  tags:
    description: 'The tags you want to associate to your "device"'
    required: false
  version:
    description: 'Tailscale version to use.'
    required: true
    default: '1.14.0'
runs:
    using: 'composite'
    steps:
      - name: Download Tailscale
        shell: bash
        id: download
        env:
          VERSION: ${{ inputs.version }}
        run: |
          MINOR=$(echo "$VERSION" | awk -F '.' {'print $2'})
          if [ $((MINOR % 2)) -eq 0 ]; then
            URL="https://pkgs.tailscale.com/stable/tailscale_${VERSION}_amd64.tgz"
          else
            URL="https://pkgs.tailscale.com/unstable/tailscale_${VERSION}_amd64.tgz"
          fi
          curl "$URL" -o tailscale.tgz
          tar -C /tmp -xzf tailscale.tgz
          rm tailscale.tgz
          TSPATH=/tmp/tailscale_${VERSION}_amd64
          sudo mv "${TSPATH}/tailscale" "${TSPATH}/tailscaled" /usr/bin
      - name: Run Tailscale
        shell: bash
        env:
          TAILSCALE_AUTHKEY: ${{ inputs.authkey }}
          TAILSCALE_TAGS: ${{ inputs.tags }}
        run: |
          sudo tailscaled 2>~/tailscaled.log &
          HOSTNAME="github-$(cat /etc/hostname)"
          until sudo tailscale up --authkey ${TAILSCALE_AUTHKEY} --hostname=${HOSTNAME} --advertise-tags="${TAILSCALE_TAGS}" --accept-routes
          do
            sleep 0.5
          done
